name: 重建Debian

on:
  repository_dispatch:
  workflow_dispatch:
  
env:
  DEBIAN_IMAGE: debian
  TAG: bullseye
  DIY_DIR: diy
  DIY_SH: novnc.sh
  TZ: Asia/Shanghai
  
jobs:
  download-add-rebuild-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 下载镜像文件
        run: |
          docker pull ${DEBIAN_IMAGE}:${TAG}
          image_id=$(docker images | grep -v IMAGE | awk '{print $3}')
          echo "IMG_ID=${image_id}" >> $GITHUB_ENV

      - name: 添加文件
        run: |
          docker cp $GITHUB_WORKSPACE/${DIY_DIR}/${DIY_SH} ${IMG_ID}:/
          
      - name: 重建镜像
        run: |
          docker buildx build --push --tag ${DEBIAN_IMAGE}_${TAG}:rebuilt --tag ${{ github.repository }}:${{ github.ref_name }}.
          
      - name: 上传release
        if: ${{ startsWith(github.ref,'refs/tags/') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${DEBIAN_IMAGE}_${TAG}:rebuilt
          asset_name: ${DEBIAN_IMAGE}_${TAG}_rebuilt.tar
          asset_content_type: application/vnd.docker.image.rootfs.diff.tar.gzip
