name: 重建Debian

on:
  repository_dispatch:
  workflow_dispatch:
  
env:
  DEBIAN_IMAGE: debian
  TAG: bullseye
  DIY_DIR: diy
  DIY_SH: novnc.sh
  BRANCH: dist-amd64
  REPO_URL: https://github.com/debuerreotype/docker-debian-artifacts
  TZ: Asia/Shanghai
  
jobs:
  download-add-rebuild-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 下载debian仓库
        run: |
          git clone -b ${BRANCH} ${REPO_URL}
          cd docker-debian-artifacts
          cd ${TAG}
          
      - name: 添加文件
        run: |
          mkdir -p ${DIY_DIR}
          cp $GITHUB_WORKSPACE/${DIY_DIR}/${DIY_SH} ${DIY_DIR}/${DIY_SH}
          
      - name: 生成镜像
        run: |
          docker build -t ${DEBIAN_IMAGE}_rebuilt 
          
      - name: 上传release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${DEBIAN_IMAGE}_${TAG}:rebuilt
          asset_name: ${DEBIAN_IMAGE}_${TAG}_rebuilt.tar
          asset_content_type: application/vnd.docker.image.rootfs.diff.tar.gzip
