name: 重建Debian

on:
  repository_dispatch:
  workflow_dispatch:
  
env:
  DEBIAN_IMAGE: debian
  TAG: bullseye
  DIY_DIR: diy
  DIY_SH: novnc.sh
  WORKDIR: debian
  BRANCH: dist-amd64
  REPO_URL: https://github.com/debuerreotype/docker-debian-artifacts
  TZ: Asia/Shanghai
  
jobs:
  download-add-rebuild-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 下载debian仓库
        run: |
          git clone -b ${BRANCH} ${REPO_URL} ${WORKDIR}
          
      - name: 添加文件
        run: |
          cd ${WORKDIR}
          cd ${TAG}
          mkdir -p ${DIY_DIR}
          cp $GITHUB_WORKSPACE/${DIY_DIR}/${DIY_SH} ./${DIY_DIR}/${DIY_SH}
          
      - name: 生成镜像
        id: tag
        run: |
          cd ${WORKDIR}/${TAG}
          docker build -t ${DEBIAN_IMAGE}:${TAG}-rebuilt .
          docker save -o ${DEBIAN_IMAGE}:${TAG}-rebuilt.tar ${DEBIAN_IMAGE}:${TAG}-rebuilt
          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
          echo "UPLOAD_DIR=$PWD" >> $GITHUB_ENV          
          
      - name: 生成release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.TAG}}-${{ steps.tag.outputs.release_tag }}
          files: ${{env.UPLOAD_DIR}}/${{env.DEBIAN_IMAGE}}:${{env.TAG}}-rebuilt.tar
